version:  '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: P$$w0rd
    volumes:
      - mongo-data:/data/db
    
    mongo-express:
      image: mongo-express
      restart: always
      ports: 
      - 8081:8081
      environment: 
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: P@$$w0rd
        ME_CONFIG_MONGODB_URL: mongodb://root:P@$$w0rd@mongo:27017/innovatube
        ME_CONFIG_BASICAUTH: false

  
  backend: 
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:    

